### ISSUE TITLE
Realm.prototype.revoke helps revoke membranes built at our new Realm boundaries.

### ISSUE THREAD

**Issue by erights** [tc39/proposal-shadowrealm#299]
The separation enforced by the new Realms makes revocation easy and cheap!

**Comment by Jack-Works** [comment]
What is Realm.revocable?

**Comment by erights** [comment]
Hi @Jack-Works it is something I just thought of today during the tc39 realm discussion, and of symbols as weakmap keys. I was thinking about the two GC problems that membranes must solve, 
   * collected unreferenced cycles that cross membrane boundaries
   * after revoking the membrane, collecting all the objects within the membrane if they become unreachable except through the revoked membrane.

That got me thinking again about the problems that @ajvincent has raised about the bookkeeping involved in building revocable membranes today. Every call to `Proxy.revocable` creates a new revoker. To revoke the membrane, you have to call all of them which means you have to keep all of them. But without retaining them or you break the other membrane gc obligation.

Then it hit me that the realm design we just approved has this magic guaranteed enforced separation of the subgraphs property. The only connectivity is via the exotic functions on, say, the blue side invoking call behavior on the yellow, and therefore for the yellow function to hold onto the captured lexical variables needed to evaluate that call behavior.

If we introduced some analog of `Proxy.revocable` for the builtin Realm mechanism, then membranes built from proxies on top would no longer need to be built from revocable proxies and would no longer need to do that bookkeeping. Instead, the build in realm revoke mechanism could atomically inactivate all those blue exotic functions and drop their pointers to the yellow functions they point to. With the realm being created without any special direct outside access, once all indirect pointers into that realm are severed, there are few gc roots left which could retain them. The promise queue is the only one I can think of. Once there are no such jobs on the promise queue, should that ever happen (no guarantee), then all the objects in the realm disappear.

Even more exciting, if the platform knows that the objects in the realm no longer have any ability to cause effects outside the realm, it is output-free computation. At that point, all these objects can be killed *even if promise jobs point at them*, since those jobs can no longer have any observable effect. These would all follow from direct platform support. Some of this is so hard to shim that I doubt anyone will.

All the storage taken up by a plugin loaded into a realm is guaranteed to be reclaimed once that realm is revoked. This is cool!

See https://www.youtube.com/watch?v=oBqeDYETXME&list=PLKr-mvz8uvUgybLg53lgXSeLOp4BiwvB2&t=1574 from 26:14 to 28:16 . (Though of course I'll recommend the whole talk ;). Notice the year!)

**Comment by ajvincent** [comment]
@erights I haven't yet put a lot of thought into actively trying to integrate Realms with membranes, except as a concept.  This idea here is a slam-dunk winner for membranes built on top of Realms.  I'd go so far as to say that having a revoke() method built into each Realm from the start, _without_ requiring a `Realm.revocable()` call, would be worth it.

I personally see the `Proxy.revocable()` addition as an unfortunate necessity, since the `new Proxy()` API was already in place when the need for a revocable proxy arose.  If ECMAScript requires all realms be revocable, that would be very desirable in my opinion.

**Comment by erights** [comment]
Agreed. `realmInstance.revoke()` is a much better API.

**Comment by ajvincent** [comment]
Except we want to be sure that revoke function isn't exposed to the realm itself.  I wouldn't encourage self-destructing realms!  (This comment is exclusively from my lack of understanding of realms, and should be taken with a grain of salt.)

**Comment by erights** [comment]
When the blue realm creates the yellow realm, the realm object that represents the yellow realm is only a blue object in the blue realm. It is not accessible by default in the yellow realm. (And of course it is never directly accessible from the yellow realm)

**Comment by ljharb** [comment]
(`new Proxy` shipped in ES6 along with `Proxy.revocable`; it seems like it was an intentional design and not due to legacy?)

**Comment by ajvincent** [comment]
> (`new Proxy` shipped in ES6 along with `Proxy.revocable`; it seems like it was an intentional design and not due to legacy?)

Hm, I actually see why, because trying to access any property on a Proxy forwards to the shadow target, including a supposed revoke function.  So that must have been a special case need.

**Comment by erights** [comment]
I'm not suggesting that `Proxy` be changed in any way. It was intentional and necessary to build revocable membranes. But once @ajvincent explained to me the bookkeeping he was doing to use it properly, I was surprised at how painful it was. Attn @tvcutsem

**Comment by leobalter** [comment]
I like this idea a lot! I wonder if we should instead add consider `Realm.revoke(realmInstance)` or `Realm.prototype.revoke()` instead and have all Realms being revokable. These methods would be slightly analogue to detaching methods for ArrayBuffers.

My question is: if we follow the Proxy pattern, should we create 2 types of Realms, with the difference that one allows revocation and the other won't?

**Comment by erights** [comment]
I don't think there's any reason to follow the proxy pattern. Just have a Realm.prototype.revoke inherited by Realm instances. You can only revoke a realm if you have the realm instance for that realm, which initially only the realm's creator has. I don't see any reason to support irrevocable realms. The creator can simply not revoke, and not enable anyone else to revoke, if they want to prevent that. Because of the magic graph isolation property, I don't think an irrevocable realm will be any cheaper.

**Comment by ajvincent** [comment]
I have a counterpoint to offer which might complicate things.  Suppose as you do that the yellow object graph is a Realm constructed by the blue object graph, and that the blue graph has a proxy to an original object in the yellow graph.  (`addEventListener()` is my classic example, provided as a proxy callback from blue to yellow.)

Then, when the yellow graph is revoked via `yellowRealm.revoke()`, there would still be a blue proxy to the yellow event listener.

It's _probably_ still safe from an execution standpoint - the errors would be thrown from the yellow realm instead of the blue proxy, but they're still thrown - but it also could mean another small memory leak in the blue listener proxy holding a no-longer-usable shadow target for the yellow listener.

In this situation, it would probably be a very good idea to also have a `Realm.prototype.wasRevoked()` property, so that the blue proxy could auto-destruct on its next handler invocation.  

(Which leads to yet another unanswered question I've been thinking about:  what error can a membrane proxy detects that it should be revoked while in its own handler traps?  But that's a discussion for another thread.)

**Comment by erights** [comment]
While I still think this is a good idea, I was confused about the relationship between this and traditional membrane revocability. Given our two sides, blue and yellow, it was traditionally the weakmaps that held the boundary crossing links, blue-to-yellow in one weakmap and yellow-to-blue in another. These were transitionally revoked in aggregate simply by dropping the weakmaps -- such as by setting the lexical variable shared by all handlers of the same membrane to `null`. When got me thinking about all this was when @caridy explained they were using exotic callables *instead* of the weakmap. The Realm.revoke proposed here is indeed about this, since it severs all those exotic callable connections at once. All good so far.

But none of this has anything to do with `Proxy.revokable` which is solving a completely different problem. The problem is that the a blue proxy for a yellow frozen object must, under observation, produce a *blue* frozen shadow target. The properties of this shadow target, being frozen, must point at what they are observed to point at, which are other blue objects. As long as the blue proxy holds on to its shadow target, the shadow target will hold on to other blue objects. Without `Proxy.revocable` a revoked membrane can act revoked by having all its handler traps throw. If the handler do that, the shadow target is useless and can no longer be observed. But the there's no way for the proxy to actually drop it.

Even with revocable realms, the need for `Proxy.revocable` is unchanged. Everything @ajvincent says about how difficult it is to keep track of the individual revokers still holds. If we want to reduce this bookkeeping burden, we need to do something else. For example:

```js
/** I'm not seriously suggesting this name */
function makeRevocableProxyConstructionKit() {
  ...
  return { Proxy, revoke };
}
```
`makeRevocableProxyConstructionKit()` returns a pair of a `Proxy` *constructor* and a revoke function. This `Proxy.constructor` would be just like the normal `Proxy` constructor but
    * It would not have its own static `revocable` method
    * When the above `revoke` is called, all the proxies made by all the associated `Proxy` constructors are revoked.

Viola, we've moved all the painful bookkeeping into the implementation, where enough magic is available to do this bookkeeping easily. (I think. Need to check with implementors.)

**Comment by mhofman** [comment]
Is there anywhere I can read more about this bookkeeping? I'm wondering why a single `Set` with the `revoke` functions for all the proxies associated to a certain realm isn't enough? I suppose with a `FinalizationRegistry` to remove these revoke functions from the Set once the corresponding Proxy object is collected.

**Comment by caridy** [comment]
I must be missing something trivial here it seems. I'm with @mhofman, this can be done easily in user-land (even when implementing a membrane - I promise I will do it once I get back from vacation), and you don't need anything special, you just need to release the Realm instance itself, and GC should be able to aggressively collect everything, unless you are holding a exotic wrapper function in the incubator realm for whatever reason.

**Comment by ajvincent** [comment]
I don't think my counterpoint is making sense to a lot of people, so I will try again here.  I think of revocation for membranes as a two-dimensional problem:  you can revoke all the proxies in a particular realm by the proposals @erights is bringing easily enough, but when a non-proxy object in that realm is revoked, the proxies in **other** realms for that non-proxy object need revocation as well.

Consider this visualization of realms, membrane proxies and target objects.

<table>
<tr><th>Blue</th><th>Yellow</th><th>Green</th></tr>
<tr><td>o</td><td>x</td><td></td></tr>
<tr><td></td><td>x</td><td></td></tr>
<tr><td>x</td><td>o</td><td>x</td></tr>
<tr><td></td><td>x</td><td></td></tr>
<tr><td>x</td><td>o</td><td>x</td></tr>
</table>

- Each "x" is a proxy with a shadow target (in the same realm as the proxy, which turns out to be important).
- Each "o" is a non-proxy target object.
- Each row represent a proxy cylinder (what I used to call a proxy mapping) tying one proxy per object graph to its actual target
- Each column represents a realm (or object graph) in this conversation.

So the revokers for each proxy have to be available to two sources of revocation:
- The realm / object graph which owns a proxy
- The underlying target object.

When I revoke the second column's realm, I have to iterate _vertically_ and revoke each proxy in that column (each "x"), but whenever I hit a non-proxy object (the "o"), I have to spread out _horizontally_ to revoke the proxies in other realms / graphs as well.

Mark's original proposal here solves the vertical revocation, and it's quite nice in my opinion.  But that horizontal revocation is still out there.  

Mark's new Proxy constructor idea actually works _against_ this model:  if the proxy construction never provides an independent revoker, then I can't do that horizontal revocation across object graphs.

To me, a good solution is to give each realm an `.addRevoker(revoker)` method in addition to the `.revoke()` method Mark is proposing.

**Comment by mhofman** [comment]
The way I understand it, `Realm.prototype.revoke` would operate at a different layer than Proxy revokers.

As @erights mentioned, realm revocability only helps severing the links between realms, it doesn't sever any references to local shadow targets of proxies for other realm's objects. The proxies and shadow targets are part of the membrane layer, and it doesn't really matter if they represent an object in another realm, or in another machine. Using `Set`s in each realm of the revokers of proxies for other realm's objects, it should be easy to sever these local shadow targets references that are part of the membrane layer.

In the case of Realms, proxy objects also hold an indirect strong reference to the real target object in the other realm. In the case of Callable Realms, this takes the form of the exotic wrapper function. Without Realm revocability, I imagine the above `Set`s could also hold a membrane specific revoker that would drop this indirect reference the Proxy object holds, e.g. by null-ing it out or removing it from any `WeakMap`.

However @ajvincent's description of his problem made me realize that a potential `Realm.prototype.revoke` needs to clarify what exactly it would sever.

> When I revoke the yellow realm

First, I'm not still not sure I understand the horizontal vs vertical issue. My thought was that each Realm would have a Set of revokers for each of the other realms. Blue would have 2 sets, one for each of Yellow and Green, Yellow would have 2 sets, one for each of Blue and Green, etc. If you want to cleanup the links between Blue and Yellow, Blue has to call the revokers in its set for Yellow, and Yellow has to call the revokers in its set for Blue. The only horizontal part would be if Yellow needs to be dropped from every realm, in which case the above pairs of operations need to be repeated for every other realm.

These pair of operations are what isn't clear for a potential Realm revocability. `Realm.prototype.revoke` would be invoked in the incubator realm. I assume it would at the very least neuter any local exotic function wrapping the other realm's callable. What's less clear is if it should also neuter any exotic function in the other realm that are wrapping a callable from the local realm.

We should now clarify how realms are setup in @ajvincent's example: who created which realm, who holds the `Realm` instances, aka who is the incubator? Let's assume Blue is the incubator and created Yellow. If Blue calls `yellow.revoke()`, then all the Blue exotic functions wrapping Yellow callables can have their target severed. But what should happen with Yellow exotic functions holding Blue callables? Should all those be severed as well?

Let's introduce Green back, and assume it was also created by Blue. Green can never have an exotic function directly wrapping a callable of the Yellow realm. At best it has a double wrapped Green -> Blue -> Yellow (it'd be interesting to know if engines could optimize the G->B->Y->B->G quadruple wrapping that would be required in @caridy's membrane, but that's another question).

If Yellow should be dropped completely, Blue calling `yellow.revoke()` doesn't help the first layer of exotic functions that Green has which target Yellow through Blue. If Yellow should just be dropped from Blue but kept accessible by Green, then `Realm.prototype.revoke` would sever links that are still needed.

Given the need of membranes to already keep regular proxy revokers, I'm not sure there is much benefit from a `Realm.prototype.revoke` for the membrane use case. I suppose it could be used as a nuclear option to sever all links into and out of that Realm, but the bookkeeping that revocable membranes require can probably encompass cross realm references as well.

**Comment by erights** [comment]
>  (it'd be interesting to know if engines could optimize the G->B->Y->B->G quadruple wrapping that would be required in @caridy's membrane, but that's another question)

AFAICT, the short circuiting should be the trivial naive short circuiting since it has no observable difference from the specification's full chain.

**Comment by erights** [comment]
>  I suppose it could be used as a nuclear option to sever all links into and out of that Realm

Yes. I agree that it doesn't help sever a pairwise relationship between a pair of realms. But I consider that nuclear option to actually be a common operation that will and should be used a lot. Perhaps a different adjective is called for?

The interesting this about the short circuiting mentioned above --- AFAICT the only non-trivial thing about it --- is that it would need to accumulate the full revocation set. This cannot be shortened. The revoke behavior is history sensitive in this way. But only as a set, not as a path.

**Comment by erights** [comment]
Note that this nuclear option includes not just the realm but all the realms created by that realm, since the wrapping path to the child has to go through the parent as well.

**Comment by mhofman** [comment]
> The interesting this about the short circuiting mentioned above --- AFAICT the only non-trivial thing about it --- is that it would need to accumulate the full revocation set. This cannot be shortened. The revoke behavior is history sensitive in this way. But only as a set, not as a path.

I'm not quite sure I followed. Does the following seem right?

An implementation could be to version the set of revoked realms, and gate on the version the fast path of a chain of exotic wrapper functions. When a new realm is revoked, add to the set, increment the version. When a chain is called, verify the current version, and if outdated revalidate that none of the realms in the full path are revoked.

I guess not trivial, but also not particularly onerous.

**Comment by erights** [comment]
Hi @mhofman IIUC, that would be a fine way to do it. The key is that invocation remain O(1) independent of the length of the path. It's fine if revocation must do more bookkeeping in order to enable that.

**Comment by caridy** [comment]
There will be no chain of wrappers. Keep that in mind, even though it is not specified, it is let alone intentional so engines can optimize it.

The main problem I have with any revoke-like functionality is that when provided and used by the language, it is really easy to trip down (revoking while still pending code waiting to be executed) most likely the wrong use-case to revoke. What the web does is more interesting in terms of GC, but I understand it doesn't provide the guarantees something like this will provide, but It is perfectly doable in user-land.

**Comment by littledan** [comment]
This is an interesting idea, but I'm wary of claims of cheapness. Making Proxies revokable was not free in practice. I'd prefer that we make Realm revocation a post-MVP feature, given that it's not needed for basic membrane use cases.

**Comment by erights** [comment]
post MVP sounds good to me too.

**Comment by ajvincent** [comment]
Here's a graphic I drew up quite some time ago which might help with the concepts.
https://docs.google.com/drawings/d/1is0hMFXjJX3mEj_CZcHz57ncIO21b5WR2VuxJDTrk2I/edit?usp=sharing

**Comment by erights** [comment]
Hi @ajvincent , should this be closed in favor of your support for mass proxy revocation?

**Comment by ajvincent** [comment]
@erights Sort of.  I'm thinking you should open a new issue on the same idea.  I still think this could be useful, conceptually.  

The problem with keeping this specific issue open is all the membrane baggage this issue already carries, to confuse and distract readers who aren't aware of the new proposal.

I do recognize the primary motivation for this feature _is_ membranes, so it's not a strong argument to keep it open.  I actually have thought about this a bit when preparing my stage 1 pitch for [mass proxy revocation](https://github.com/tc39/proposal-mass-proxy-revocation).  I saw revoking an object graph (a set of `Proxy` objects) as completely a separate question from revoking a `ShadowRealm`.

Here's the key question: _Is there still a generic need to revoke a `ShadowRealm`?_  Forget membranes for this question.  Would cleaning up a shadow realm in a single atomic operation be beneficial?  An analogy might be killing off a Worker or an `<iframe/>`.

**Comment by ajvincent** [comment]
You know, I just realized there's a simple, if somewhat painful, way to do this:  instead of holding direct references to a `ShadowRealm`, hold a `Proxy.revocable<ShadowRealm>` where the `ProxyHandler` is `Reflect`.  One proxy to revoke.

I'm unsure of the performance hit in this case.  But it weakens the case for this bug even further.

**Comment by mhofman** [comment]
@ajvincent i don't think that would work. The exotic function wrappers returned through the callable boundary effectively work as a limited membrane. By revoking a shadow realm instance, the semantics should be to make all these existing wrappers throw on invocations.

**Comment by caridy** [comment]
I will close it!
